AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Text Summarizer Application Backend

Parameters:
  CognitoUserPoolId:
    Type: String
    Description: ID of the Cognito User Pool
    Default: eu-north-1_O4CIZM2aJ
    
  SageMakerEndpointName:
    Type: String
    Description: Name of the SageMaker endpoint
    Default: summarizer-endpoint

Resources:
  # API Gateway for the Summarize API
  SummarizerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPoolId}
      Cors:
        AllowMethods: "'OPTIONS,POST'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigin: "'*'"

  # Lambda function to invoke the SageMaker endpoint
  SummarizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          SAGEMAKER_ENDPOINT_NAME: !Ref SageMakerEndpointName
      Policies:
        - AmazonSageMakerFullAccess
      Events:
        SummarizeAPI:
          Type: Api
          Properties:
            RestApiId: !Ref SummarizerApi
            Path: /summarize
            Method: post

  # IAM Role for the SageMaker Endpoint
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL for the production stage
    Value: !Sub https://${SummarizerApi}.execute-api.${AWS::Region}.amazonaws.com/prod/summarize
  
  SummarizerFunction:
    Description: Lambda Function ARN
    Value: !GetAtt SummarizerFunction.Arn
